# Name the stages involved in the pipeline
stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-project:
  stage: build
  image: mrcoalp/gcc-cmake-xorg:latest
  only:
    - merge_requests
    - tags
    - master
  script:
    # Debug build
    - sh build.sh --make -i
    # Release build
    - sh build.sh --make -i -r
  artifacts:
    paths:
      - build/Debug/bin/
      - build/Release/bin/
